config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: %i[create]
    resources :reviews, only: %i[create]
  end
  root "lists#index"

  resources :bookmarks, only: %i[show]
  delete "bookmarks/:id", to: "bookmarks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :list_id, presence: true
  validates :movie_id, presence: true, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :cover
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: { scope: :title }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true, comparison: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(params[:bookmark].permit(:comment, :movie_id))
    @bookmark.list = List.find(params[:list_id])
    if @bookmark.save
      redirect_to list_path(params[:list_id])
    else
      @list = List.find(params[:list_id])
      @review = Review.new
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params[:list].permit(:name, :cover))
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @review = Review.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(params[:review].permit(:rating, :comment))
    @review.list = List.find(params[:list_id])
    if @review.save
      redirect_to list_path(params[:list_id])
    else
      @list = List.find(params[:list_id])
      @bookmark = Bookmark.new
      render 'lists/show', status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6 mt-4">
      <h2>New bookmark for <%= @list.name %> list</h2>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :movie_id, as: :select, collection: Movie.all, prompt: 'Select movie', label: false %>
        <%= f.input :comment %>
        <%= f.button :submit, class: "btn btn -primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light sticky-top">
      <div class="container-fluid">
        <%= link_to image_tag("logo.jpg"), root_path %>
        <span class="navbar-text">
          <%= link_to "My lists", lists_path %>
          <%= link_to "New list", new_list_path %>
        </span>
      </div>
    </nav>
    <%= yield %>
    <br>
  </body>
</html>

app/views/lists/index.html.erb
<div class="lists-cover">
  <%= image_tag "movie-theatre-cover.jpg", alt: "Movie theatre cover picture", height: 450 %>
  <div class="cover-text">
    <h1>My lists of movies</h1>
    <p>Add any kind of movie lists</p>
  </div>
</div>
<div class="container">
  <div class="mx-5">
    <div class="flex-lists-title">
      <h4>My lists</h2>
      <%= link_to "New list", new_list_path, class: "btn btn-primary" %>
    </div>
    <div class="lists-grid">
      <% @lists.each do |list| %>
        <a href="lists/<%= list.id %>">
          <div class="card-simple">
            <% if list.cover.attached? %>
              <%= cl_image_tag list.cover.key, alt: "List #{list.cover.name}" %>
            <% end %>
            <h5><%= list.name %></h5>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6 mt-4">
      <h2>New list</h2>
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.input :cover, as: :file %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="list-cover">
  <% if @list.cover.attached? %>
    <%= cl_image_tag @list.cover.key, height: 300, alt: "Image of #{@list.cover.name}" %>
  <% end %>
  <div class="cover-text">
    <h1><%= @list.name %></h1>
  </div>
  <button type="button" class="btn btn-primary badge-top-right disabled">
    Bookmarks <span class="badge text-bg-primary"><%= @list.bookmarks.count %></span>
  </button>
</div>
<div class="container">
  <h4>Bookmarks from <%= @list.name %> list</h4>
  <div class="row justify-content-center">
    <div class="col-12 col-lg-8">
      <div class="bookmarks-grid">
        <% @list.bookmarks.each do |bookmark| %>
          <div class="card-movie">
            <img src="<%= bookmark.movie.poster_url %>" alt="Movie poster">
            <div class="card-movie-content">
              <p class="movie-title"><%= bookmark.movie.title %><span class="movie-rating"> • <%= bookmark.movie.rating %> <i class="fa-solid fa-star"></i></span></p>
              <p class="movie-overview"><%= bookmark.movie.overview %></p>
              <div class="flex-movie-footer">
                <p><i class="fa-solid fa-quote-left"></i> <%= bookmark.comment %></p>
                <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-lg-4 ps-4 mb-5">
      <h4>New bookmark for <%= @list.name %> list</h4>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :movie_id, collection: Movie.all, prompt: 'Select movie', label: false, as: :select, input_html: {data: {controller: "tom-select"}} %>
        <%= f.input :comment %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-6 pe-3">
      <h4>Reviews</h4>
      <div class="mt-4">
        <% @list.reviews.each do |review| %>
          <% @rating_stars = ""
          review.rating.times do
            @rating_stars << '<i class="fa-solid fa-star"></i>'
          end %>
          <p><%= sanitize @rating_stars %> <span style="font-size: 12px;"><%= review.created_at.strftime("Added on %m/%d/%Y at %H:%M") %></span></p>
          <p><%= review.comment %></p>
          <hr>
        <% end %>
      </div>
    </div>
    <div class="col-6 ps-3">
      <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate this list", input_html: {data: {controller: "star-rating"}} %>
        <%= f.input :comment %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>